spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/chattingApp
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    expire: 5

  application:
    name: chattingservice

server:
  port: 8080

eureka:
  instance:
    # 표기되는 규칙 변경
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka